DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS pizzas;
DROP TABLE IF EXISTS restaurants;
DROP TABLE IF EXISTS customers;

DROP TYPE IF EXISTS order_status;
DROP TYPE IF EXISTS pizza_size;
DROP TYPE IF EXISTS pizza_type;