DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS pizzas;
DROP TABLE IF EXISTS restaurants;
DROP TABLE IF EXISTS pizza_sizes;
DROP TABLE IF EXISTS pizza_types;
DROP TABLE IF EXISTS customers;

DROP TYPE IF EXISTS order_status;